import { Car } from "./types";

export const MOCK_CARS: Car[] = [
  {
    id: "1",
    title: "Škoda Octavia Combi 2.0 TDI",
    brand: "Škoda",
    model: "Octavia",
    year: 2021,
    mileage: 48000,
    price: 489000,
    fuelType: "Diesel",
    transmission: "Automatická",
    bodyType: "Combi",
    color: "Šedá metalíza",
    engineSize: "2.0",
    power: 150,
    imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    sautoUrl: "https://www.sauto.cz/detail-prodejce/autobazar-hk-sro/8877",
    description: "Velmi zachovalý vůz v prvním vlastnictví. Servisní knížka, nová STK do 2026.",
  },
  {
    id: "2",
    title: "Volkswagen Golf 1.5 TSI",
    brand: "Volkswagen",
    model: "Golf",
    year: 2020,
    mileage: 62000,
    price: 429000,
    fuelType: "Benzín",
    transmission: "Manuální",
    bodyType: "Hatchback",
    color: "Bílá",
    engineSize: "1.5",
    power: 130,
    imageUrl: "https://images.unsplash.com/photo-1617469767302-a6fe4ecfaa28?w=800&q=80",
    sautoUrl: "https://www.sauto.cz/detail-prodejce/autobazar-hk-sro/8877",
    description: "Plná výbava, panoramatická střecha, vyhřívané sedačky, 2 sady pneumatik.",
  },
  {
    id: "3",
    title: "Toyota Corolla 1.8 Hybrid",
    brand: "Toyota",
    model: "Corolla",
    year: 2022,
    mileage: 31000,
    price: 569000,
    fuelType: "Hybrid",
    transmission: "Automatická",
    bodyType: "Sedan",
    color: "Modrá metalíza",
    engineSize: "1.8",
    power: 122,
    imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    sautoUrl: "https://www.sauto.cz/detail-prodejce/autobazar-hk-sro/8877",
    description: "Hybrid v záruce Toyota. Nízká spotřeba, bezproblémový provoz.",
  },
  {
    id: "4",
    title: "Ford Focus Combi 1.5 EcoBoost",
    brand: "Ford",
    model: "Focus",
    year: 2019,
    mileage: 87000,
    price: 319000,
    fuelType: "Benzín",
    transmission: "Manuální",
    bodyType: "Combi",
    color: "Červená",
    engineSize: "1.5",
    power: 150,
    imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    sautoUrl: "https://www.sauto.cz/detail-prodejce/autobazar-hk-sro/8877",
    description: "Prostorné kombi, výborný stav, 4 nové pneumatiky, nedávná výměna oleje.",
  },
  {
    id: "5",
    title: "Hyundai Tucson 1.6 T-GDI 4x4",
    brand: "Hyundai",
    model: "Tucson",
    year: 2021,
    mileage: 39000,
    price: 649000,
    fuelType: "Benzín",
    transmission: "Automatická",
    bodyType: "SUV",
    color: "Černá metalíza",
    engineSize: "1.6",
    power: 177,
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    sautoUrl: "https://www.sauto.cz/detail-prodejce/autobazar-hk-sro/8877",
    description: "Plná výbava, pohon 4x4, výhřev celého interiéru, záruční servis.",
  },
  {
    id: "6",
    title: "Kia Ceed SW 1.4 T-GDI",
    brand: "Kia",
    model: "Ceed",
    year: 2020,
    mileage: 55000,
    price: 369000,
    fuelType: "Benzín",
    transmission: "Manuální",
    bodyType: "Combi",
    color: "Šedá",
    engineSize: "1.4",
    power: 140,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    sautoUrl: "https://www.sauto.cz/detail-prodejce/autobazar-hk-sro/8877",
    description: "7letá záruka Kia, servisní záznamy, navigace, kamera dozadu.",
  },
];
